server:
  port: 9000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://example.org
          predicates:
            - Cookie=mycookie,mycookievalue
        - id: path_route
          uri: http://127.0.0.1:9000
          predicates:
            - Path= /testPath/**