spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.129.201.48/test?characterEncoding=utf8
    username:janle
    password:
