spring:
  application:
    #注册引用的名称
    name: sc-demo-euerka-providor
eureka:
  client:
    service-url:
     #这里配置两个地址，也就是两个注册server的地址
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/
  instance:
    #表示自己的ip注测到微服务所在的操作系统的hostname到EurekaClient
    prefer-ip-address: true